# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.Hospital.example.com:
    container_name: peer0.Hospital.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Hospital.example.com
      - CORE_PEER_ADDRESS=peer0.Hospital.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Hospital.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Hospital.example.com:9051
      # - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Hospital.example.com:7051
      - CORE_PEER_LOCALMSPID=HospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Hospital.example.com/peers/peer0.Hospital.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Hospital.example.com/peers/peer0.Hospital.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.Hospital.example.com:/var/hyperledger/production
    ports:
      - 7051:7051



  peer0.Pharma.example.com:
    container_name: peer0.Pharma.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Pharma.example.com
      - CORE_PEER_ADDRESS=peer0.Pharma.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Pharma.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      # - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Pharma.example.com:9051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Pharma.example.com:10051
      - CORE_PEER_LOCALMSPID=PharmaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Pharma.example.com/peers/peer0.Pharma.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Pharma.example.com/peers/peer0.Pharma.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.Pharma.example.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer0.Insurance.example.com:
    container_name: peer0.Insurance.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Insurance.example.com
      - CORE_PEER_ADDRESS=peer0.Insurance.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Insurance.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      # - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Insurance.example.com:10051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Insurance.example.com:9051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Insurance.example.com/peers/peer0.Insurance.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Insurance.example.com/peers/peer0.Insurance.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.Insurance.example.com:/var/hyperledger/production
    ports:
      - 10051:10051
